### ISSUE TITLE
Build 1128 borked it?

### ISSUE THREAD

**Issue by ShiroXOkami** [benaclejames/VRCThumbParams#10]
i could be losing it but i had it working just fine in build 1127 but now it wont read at all no matter what i do

**Comment by benaclejames** [comment]
Weird, still works perfectly fine for me! Check for conflicting mods!

**Comment by ShiroXOkami** [comment]
Copy that. Are there any common conflicts you know of off the top of your head? Just to narrow the search~

**Comment by benaclejames** [comment]
Not to my knowledge, though depends on what exactly about the mod isn't working. If it's just the blendshapes, it could be vertex animation disabler. Other than that, I'm clueless haha

**Comment by ShiroXOkami** [comment]
Basically when I load in the debug menu doesn't change the integer when touching the capacitors. Detects the gesture value and the gesture weight but not the thumb value. I have no idea if that helps
