### ISSUE TITLE
Broken after patch

### ISSUE THREAD

**Issue by ghost** [benaclejames/VRCThumbParams#3]
No longer functional on current VRChat Build 1061. Seems like others are having the same issue.

**Comment by benaclejames** [comment]
Oops! Not sure how I missed this 😂
I've updated the [latest release](https://github.com/benaclejames/VRCThumbParams/releases/tag/v1.1.3) with the fix. Thanks for letting me know and apologies for the inconvenience.

**Comment by ghost** [comment]
No worries!
